#server:
#  port: 8080 # web服务器端口
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.132:3306/iot?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password:
#  redis:
#    host: 192.168.1.111
#    port: 6379
#    password: # redis 密码

#m2miot:
#  activemq:
#    broker-url: tcp://192.168.1.132:61616
#    user:    # activemq 用户名
#    password: # activemq 密码

#vertx:
#  tcp:
#    log-activity: true # tcp 网络通信日志
#    port: 51000 # tcp 服务器端口
#  mqtt:
#    port: 1883 # mqtt 服务器端口
#    log-activity: true # mqtt 网络通信日志

